---
- hosts: localhost
  connection: local
  become: True

  tasks:
    - name: Install rpm-fusion repositories
      dnf:
        enablerepo: 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm'
